[project]
name = "mcp-liveclass"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain>=0.3.27",
    "langchain-groq>=0.3.8",
    "langchain-mcp-adapters>=0.1.10",
    "langgraph>=0.6.7",
    "mcp>=1.15.0",
]
